#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_ENV_PATH="$ROOT_DIR/.env"
ROOT_ENV_EXAMPLE_PATH="$ROOT_DIR/.env.example"
API_ENV_PATH="$ROOT_DIR/apps/api/.env"
WEB_ENV_PATH="$ROOT_DIR/apps/web/.env"

if [[ ! -f "$ROOT_ENV_PATH" ]]; then
  cp "$ROOT_ENV_EXAMPLE_PATH" "$ROOT_ENV_PATH"
  echo "Created $ROOT_ENV_PATH from .env.example"
fi

set -a
source "$ROOT_ENV_PATH"
set +a

POSTGRES_DB="${POSTGRES_DB:-risk_atlas}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-postgres}"
POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5433}"
API_HOST="${API_HOST:-0.0.0.0}"
API_PORT="${API_PORT:-3000}"
WEB_PORT="${WEB_PORT:-5173}"
VITE_API_BASE_URL="${VITE_API_BASE_URL:-http://localhost:${API_PORT}}"
VITE_REPOSITORY_URL="${VITE_REPOSITORY_URL:-}"
RISK_ATLAS_INVITE_CODES="${RISK_ATLAS_INVITE_CODES:-risk-atlas-demo-2026,3191-4b0d-8461}"
RISK_ATLAS_INVITE_SALT="${RISK_ATLAS_INVITE_SALT:-risk_atlas_v2_invite_salt}"

cat > "$API_ENV_PATH" <<EOF
PORT=${API_PORT}
HOST=${API_HOST}
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
RISK_ATLAS_INVITE_CODES=${RISK_ATLAS_INVITE_CODES}
RISK_ATLAS_INVITE_SALT=${RISK_ATLAS_INVITE_SALT}
EOF

cat > "$WEB_ENV_PATH" <<EOF
WEB_PORT=${WEB_PORT}
VITE_API_BASE_URL=${VITE_API_BASE_URL}
VITE_REPOSITORY_URL=${VITE_REPOSITORY_URL}
EOF

echo "Wrote $API_ENV_PATH"
echo "Wrote $WEB_ENV_PATH"